# name of the software
name: Artemis OS Wiki

project:
  version: 1.0.0
  download_url: documentation/download.html
  download_text: Download

license:
  software: MIT License
  software_url: https://opensource.org/licenses/MIT

  docs: CC BY 3.0
  docs_url: https://creativecommons.org/licenses/by/3.0/


links:
  header:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/Artemis-OS-Linux
  homepage:
    - title: View on GitHub
      icon: github
      brand: true
      url: https://github.com/Artemis-OS-Linux
  footer:
    - title: GitHub
      icon: github
      brand: true
      url: https://github.com/Artemis-OS-Linux
    - title: Issues
      icon: bug
      url: https://github.com/Artemis-OS-Linux/Artemis-OS-Support/issues?q=is%3Aopen

ui:
  mode: 'dark' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
  github:
    user: Artemis OS
    repo: artemis-os-linux.github.io
  twitter:
    enabled: false
    via:
    hash:
    account:
  facebook:
    enabled: false
    profileUrl:

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
