title: jekyll-theme-read-the-docs
description: Read the Docs like Jekyll Theme for GitHub Pages

theme: null

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - .bash
  - .github
  - .vscode
  - .yarn
  - CNAME
  - Gemfile
  - Gemfile.lock
  - jekyll-theme-read-the-docs.gemspec
  - LICENSE
  - Makefile
  - node_modules
  - package-lock.json
  - package.json
  - Pipfile
  - Pipfile.lock
  - requirements.txt
  - webpack.config.js
  - yarn.lock
